/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <MainWindowDLG.h>
#include "DIALOG.h"
#include "WM.h"
#include "img.h"
#include <string.h>
#include <stdio.h>


#define X_START 	15
#define Y_START 	40
#define LEGEND_D_X	10
#define	LEGEND_D_Y	0
#define	LEGEND_W	30
#define LEGEND_X0	(X_START+(PX_X*PX_SIZE)+LEGEND_D_X)
#define LEGEND_Y0	(Y_START+LEGEND_D_Y)
#define SCALE_W		5
#define SCALE_D		4
#define SCALE_T		2
#define SCALE_N		9
#define SCALE_X0	(LEGEND_X0+LEGEND_W+SCALE_D)
#define SCALE_S		(255/(SCALE_N-1))
#define TXT_D	2
#define TXT_S	60
#define TXT_Y0	LEGEND_Y0-8
#define TXT_X0	SCALE_X0+SCALE_W+TXT_D
#define BCKG_COLOR GUI_WHITE
#define FRNT_COLOR GUI_BLACK
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "MainWindow", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnSettings", ID_BUTTON_2, LEGEND_X0, LEGEND_Y0+250+7, 32, 32, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "T0", ID_EDIT_0, TXT_X0, TXT_Y0, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "T1", ID_EDIT_1, TXT_X0, (TXT_Y0+TXT_S), 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "T2", ID_EDIT_2, TXT_X0, (TXT_Y0+(2*TXT_S)), 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "T3", ID_EDIT_3, TXT_X0, (TXT_Y0+(3*TXT_S)), 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "T4", ID_EDIT_4, TXT_X0, (TXT_Y0+(4*TXT_S)), 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Title", ID_TEXT_3, 15, 5, 700, 30, 0, 0x64, 0 },
  { IMAGE_CreateIndirect, "ImageSensor", ID_IMAGE_0, 550, 40, 172, 288, 0, 0, 0 },
  { IMAGE_CreateIndirect, "ImageSTM32", ID_IMAGE_1, 15, 340, 218, 80, 0, 0, 0 },
  { IMAGE_CreateIndirect, "ImageSegger", ID_IMAGE_2, 285, 360, 123, 80, 0, 0, 0 },
  { IMAGE_CreateIndirect, "ImageMikroe", ID_IMAGE_3, 470, 360, 299, 80, 0, 0, 0 },
  { BUTTON_CreateIndirect, "btnCapture", ID_BUTTON_3, 730, 5, 60, 60, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


// USER START (Optionally insert additional static code)
extern GUI_CONST_STORAGE GUI_BITMAP bmset;
extern GUI_CONST_STORAGE GUI_BITMAP bmsensor;
extern GUI_CONST_STORAGE GUI_BITMAP bmstm32;
extern GUI_CONST_STORAGE GUI_BITMAP bmsegger;
extern GUI_CONST_STORAGE GUI_BITMAP bmmikroe;
extern GUI_CONST_STORAGE GUI_BITMAP bmcapture;

GUI_RECT rectImage = {X_START, Y_START, X_START+PX_X*(PX_SIZE), Y_START+PX_Y*(PX_SIZE)}; //Drawing Area for image
GUI_RECT rectLegend = {LEGEND_X0, LEGEND_Y0, SCALE_X0+SCALE_W, LEGEND_Y0+255};	//Drawing Area for legend

void updateLabels(WM_HWIN hWin, float min, float max)
{
	float x=(max-min)/4;	//there are 5 labels
	char str[5];

	sprintf((char *)str, "%d", (int)max);
	EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_0), str);

	sprintf((char *)str, "%d", (int)(max-x));
	EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_1), str);

	sprintf((char *)str, "%d", (int)(min+2*x));
	EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_2), str);

	sprintf((char *)str, "%d", (int)(min+x));
	EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_3), str);

	sprintf((char *)str, "%d", (int)(min));
	EDIT_SetText(WM_GetDialogItem(hWin, ID_EDIT_4), str);
}

void invalidateLegend(WM_HWIN hWin)
{
	WM_InvalidateRect(hWin, &rectLegend); //trigger drawing in area for legend
}

void drawLegend(void) //executes in WM_PAINT when triggered
{
	uint32_t legendColor=0;
	int i;

	GUI_SetPenSize(1);
	for(i=0; i<255; i++)
	{
		legendColor=getPixelColor(255-i);
		GUI_SetColor(legendColor);
		GUI_DrawHLine(LEGEND_Y0+i, LEGEND_X0, LEGEND_X0+LEGEND_W);
	}

	GUI_SetPenSize(2);
	GUI_SetColor(FRNT_COLOR);
	for(i=0; i<SCALE_N; i++)
	{
		GUI_DrawLine(SCALE_X0, LEGEND_Y0+i*SCALE_S, SCALE_X0+SCALE_W, LEGEND_Y0+i*SCALE_S);
	}
	GUI_DrawLine(SCALE_X0, LEGEND_Y0, SCALE_X0, LEGEND_Y0+(SCALE_N-1)*SCALE_S);
}

void invalidateImage(WM_HWIN hWin)
{
	 WM_InvalidateRect(hWin, &rectImage); //trigger drawing in area for image
}

void drawImage(void) //executes in WM_PAINT when triggered
{
	 int i, j;
	 int x,y,w,h,pixel_size;

	 if(getInterpolate())pixel_size=PX_SIZE/INT_POINTS;
	 else pixel_size=PX_SIZE;

	 w=IMG_X_SIZE/pixel_size;
	 h=IMG_Y_SIZE/pixel_size;

	 x=X_START;
	 y=Y_START;

	 for(i=0; i<h; i++)
	 {
		 for(j=0; j<w; j++)
		 {
			 GUI_SetColor(getPixelColor(getImagePixel(j,i))); //set color of pixel from matrix
			 GUI_FillRect(x,y,x+pixel_size,y+pixel_size); //draw it
			 x+=(pixel_size);
		 }
		 y+=(pixel_size);
		 x=X_START;
	 }
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN      hItem;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MainWindow'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, BCKG_COLOR);
    //
    // Initialization of 'Images'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmsensor);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    IMAGE_SetBitmap(hItem, &bmstm32);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
    IMAGE_SetBitmap(hItem, &bmsegger);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
    IMAGE_SetBitmap(hItem, &bmmikroe);
    //
    // Initialization of 'Buttons'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "");
    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmset, 1, 1);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "");
    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmcapture, 5, 5);
    //
    // Initialization of 'Edits'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "40");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, FRNT_COLOR);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, BCKG_COLOR);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "35");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, FRNT_COLOR);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, BCKG_COLOR);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "30");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, FRNT_COLOR);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, BCKG_COLOR);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "25");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, FRNT_COLOR);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, BCKG_COLOR);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "20");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16B_1);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, FRNT_COLOR);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, BCKG_COLOR);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextColor(hItem, FRNT_COLOR);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetBkColor(hItem, BCKG_COLOR);
    TEXT_SetText(hItem, "THERMAL CAMERA - Melexis MLX90640 32x24 IR Array (IR GRID 3 click)");
    //

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;

    case WM_PAINT:
    	drawLegend();
    	drawImage();
  	 break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_2: // Notifications sent by 'Temperature'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMainWindow
*/

WM_HWIN CreateMainWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
