/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <string.h>
#include <stdio.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0       (GUI_ID_USER + 0x02)
#define ID_SLIDER_0        	(GUI_ID_USER + 0x03)
#define ID_SLIDER_1        	(GUI_ID_USER + 0x05)
#define ID_TEXT_0        	(GUI_ID_USER + 0x06)
#define ID_TEXT_1        	(GUI_ID_USER + 0x07)
#define ID_SPINBOX_0        (GUI_ID_USER + 0x08)
#define ID_SPINBOX_1        (GUI_ID_USER + 0x09)
#define ID_BUTTON_0        	(GUI_ID_USER + 0x0A)
#define ID_BUTTON_1        	(GUI_ID_USER + 0x0B)
#define ID_CHECKBOX_0		(GUI_ID_USER + 0x0C)
#define ID_CHECKBOX_1		(GUI_ID_USER + 0x0D)
#define	ID_TEXT_2			(GUI_ID_USER + 0x0E)
#define ID_DROPDOWN_0		(GUI_ID_USER + 0x0F)

// USER START (Optionally insert additional defines)
WM_HWIN CreateSettings(void);
// USER END

